 update ElectricityMeterMaster set SetID = 2 where MeterName = 'Hospital LT With Makeup Room 201,202 & 203'
update ElectricityMeterMaster set SetID = 2 where MeterName = 'Hospital Out Door'
update ElectricityMeterMaster set SetID = 7 where MeterName = 'Bungalow 1 LT'
update ElectricityMeterMaster set SetID = 7 where MeterName = 'Bungalow 1 Out Door'
update ElectricityMeterMaster set SetID = 6 where MeterName = 'Office Set'
update ElectricityMeterMaster set SetID = 1 where MeterName = 'Police Station'
update ElectricityMeterMaster set SetID = 11 where MeterName = '8000 sqft'
update ElectricityMeterMaster set SetID = 9 where MeterName = 'Restaurant'
update ElectricityMeterMaster set SetID = 5 where MeterName = 'Parsi Bungalow AC'
update ElectricityMeterMaster set SetID = 5 where MeterName = 'Parsi Bungalow Light'
update ElectricityMeterMaster set SetID = 4 where MeterName = 'Bungalow 2 LT'
update ElectricityMeterMaster set SetID = 4 where MeterName = 'Bungalow 2 Makeup Room'
update ElectricityMeterMaster set SetID = 8 where MeterName = 'Villa Set AC'
update ElectricityMeterMaster set SetID = 8 where MeterName = 'Villa Set Light'
update ElectricityMeterMaster set SetID = 8 where MeterName = 'Villa Set Out Door'
